### ISSUE TITLE
NoClassDefFoundError with RxJava

### ISSUE THREAD

**Issue by ZakTaccardi** [cantrowitz/RxBroadcast#15]
`java.lang.NoClassDefFoundError: Failed resolution of: Lrx/AsyncEmitter$BackpressureMode;`

Because of https://github.com/ReactiveX/RxJava/pull/4580/files

**Comment by ZakTaccardi** [comment]
(on rxJava v1.2.5)

**Comment by ZakTaccardi** [comment]
oops - duplicate of https://github.com/cantrowitz/RxBroadcast/issues/13

**Comment by cantrowitz** [comment]
The new version is out on maven. Let me know of it isn't there

**Comment by ZakTaccardi** [comment]
I don't see it yet

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.cantrowitz%22%20AND%20a%3A%22rxbroadcast%22

**Comment by cantrowitz** [comment]
seems like an issue with sonatype. Created an issue https://issues.sonatype.org/browse/MVNCENTRAL-1516

**Comment by aphexcx** [comment]
I don't see 1.2.5 on maven - has it been published?

**Comment by cantrowitz** [comment]
1.1.1 is the latest. We aren't tracking rxjava.
