### ISSUE TITLE
RxBroadcast breaks w/rxJava 1.3.0

### ISSUE THREAD

**Issue by tellypresence** [cantrowitz/RxBroadcast#18]
With RxBroadcast version: 1.1.1, RxJava version: 1.2.6, project builds fine.

But with RxJava 1.3.0 get error:
`java.lang.NoSuchMethodError: No static method 
    fromEmitter(Lrx/functions/Action1;Lrx/Emitter$BackpressureMode;)Lrx/Observable;
in class Lrx/Observable; or its super classes
`

**Comment by cantrowitz** [comment]
closed with #17
