### ISSUE TITLE
Sample for broadcast receiver for Sending SMS

### ISSUE THREAD

**Issue by carmas123** [cantrowitz/RxBroadcast#7]
I try to use your lib to receive a broadcast when I send an SMS with PendingIntent (I use Kotlin):

```
        mBroadCast = RxBroadcast.fromBroadcast(ctx, IntentFilter(SENT)).subscribe {
            val idSms = it.extras.getString("sms_id")
            logd(idSms)
        }
```

all work fine the only problem is that I cannot get the "BroadcastReceiver resultcode" to handle the sending sms result.

Please can you help me?

**Comment by cantrowitz** [comment]
I'm sorry I don't understand the question. Can you please send me all of
the code and where you are not getting what you need?

**Comment by carmas123** [comment]
To create a receiver (Non reactive) I do this:

```
registerReceiver(object : BroadcastReceiver() {
            override fun onReceive(context: Context, intent: Intent) {
                var result = ""

                when (resultCode) {
                    Activity.RESULT_OK -> result = "Transmission successful"
                    SmsManager.RESULT_ERROR_GENERIC_FAILURE -> result = "Transmission failed"
                    SmsManager.RESULT_ERROR_RADIO_OFF -> result = "Radio off"
                    SmsManager.RESULT_ERROR_NULL_PDU -> result = "No PDU defined"
                    SmsManager.RESULT_ERROR_NO_SERVICE -> result = "No service"
                    5 ->
                        result = "Limit Exceeded"
                }

            }
        }, IntentFilter(SENT))
```

in "resultCode" I've the SmsManager.sendTextMessage result.

How can I do this with your lib?

**Comment by cantrowitz** [comment]
Result code is coming from outside of this receiver. I'd suggest examining
the result code in onActivityResult and using that logic to later register
different receivers

**Comment by cantrowitz** [comment]
You could also do a combineWithLatest of the RxBroadcast and the activity's Result. But this really doesn't belong in this particular library so I'm closing this.
