### ISSUE TITLE
rxjava2

### ISSUE THREAD

**Issue by andreya108** [cantrowitz/RxBroadcast#8]
Hi!

Will you update your lib for RxJava 2?

**Comment by cantrowitz** [comment]
accepting pull requests!

**Comment by andreya108** [comment]
Done!

**Comment by cantrowitz** [comment]
pending #9 completes CI pass. Will merge when done.

**Comment by andreya108** [comment]
Thanks!

**Comment by andreya108** [comment]
Just noticed, I forgot to change README.md.
When new lib will be available in global repos?

**Comment by cantrowitz** [comment]
I have updated and released. It should be there in a few hours or so

**Comment by andreya108** [comment]
Thanks!

In README.md in **Unregistering** section:
`Disposable` is returned on `subscribe()` instead of `Subscription` in RxJava2:

`Disposable disposable = RxBroadcast.fromLocalBroadcast(context, intentFilter).subscribe(...);`
...

``` @Override
  protected void onStop() {
    super.onStop();

    if (disposable != null) {
      disposable.dispose();
    }
  }
```

**Comment by cantrowitz** [comment]
#10
